// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// FileCreateOpener is an autogenerated mock type for the FileCreateOpener type
type FileCreateOpener struct {
	mock.Mock
}

// OpenCreate provides a mock function with given fields: path
func (_m *FileCreateOpener) OpenCreate(path string) (io.WriteCloser, error) {
	ret := _m.Called(path)

	var r0 io.WriteCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.WriteCloser, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) io.WriteCloser); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.WriteCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileCreateOpener interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileCreateOpener creates a new instance of FileCreateOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileCreateOpener(t mockConstructorTestingTNewFileCreateOpener) *FileCreateOpener {
	mock := &FileCreateOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
